Table Clearing Planning Module: CTableClearingPlanning Class Reference
CTableClearingPlanning Class Reference
This class computes the predicates of the table top objects for the planning part The class needs as input the segmented objects and the table plane coefficients. Be sure to given the objects in input with respect the desired reference frame.
#include <table_clearing_planning.h>
Data Structures
struct EndEffector
Structure to define the end effector model.
struct FclMesh
struct GripperModel
Structure to define the gripper model.
Public Member Functions
CTableClearingPlanning (std::vector< PointCloudT > &objects)
Initialize the class with the objects.
void setGripperSimpleModel (double height, double deep, double width, double distance_plane)
Set the gripper model.
void setGripperModel (double opening_width, double closing_width, double finger_width, double deep, double height, double closing_height)
Set the fingers model.
void setPlanePointCloud (PointCloudT plane_cloud)
Set the plane point cloud.
void setOriginalPointCloud (PointCloudT original_cloud)
Set the original point cloud, the one used for the segmentation.
void setObjectsPointCloud (std::vector< PointCloudT > &objects, bool convert_to_label=false)
set point clouds of the objects, reference to project the principal direction to the plane: http://www.maplesoft.com/support/help/Maple/view.aspx?path=MathApps%2FProjectionOfVectorOntoPlane
void setPlaneCoefficients (pcl::ModelCoefficients &plane_coefficients)
Set the coefficients of the table plane.
void testTranslation (uint idx)
void testFclDistance ()
Function to test the distance of FCL for two simple mesh models.
void computeOBBObjects (bool refine_centroids=true)
Compute the Axis Aligned Bounding Box of each object.
void computeSimpleHeuristicGraspingPoses (bool vertical_poses=PCA_GRASPING)
Compute the grasping pose with a simple heuristic.
void computeConvexHulls (bool rand_=true)
Compute the convex hull of each object.
void computeConcaveHulls ()
Compute the concave hull of each object.
void computeProjectionsOnTable ()
Compute the projections of the objects onto the table plane.
void computeProjectionsConvexHull ()
Compute the convex hulls of the projections onto the table plane.
void computeRichConvexHulls (bool rand_=true)
Compute the convex hull of each object considering also the projections of the convex hulls on the plane. These points are then added to the original point cloud and the convex hull is recomputed. IMPORTANT: we can project all the coud and do the convex hull, so it is computed only once.
void computeRichConcaveHulls ()
Compute the concave hull of each object considering also the projections of the convex hulls on the plane. These points are then added to the original point cloud and the convex hull is recomputed. IMPORTANT: THE CONCAVE HULL IS NOT WELL IMPLEMENTED SEE: http://www.pointclouds.org/blog/gsoc/goleary/tutorials/concave_hull.php.
void computeOnTopPredicates (double th1=100, double th2=100, bool print=false)
Compute the on predicates.
void setPushingStep (double pushing_step)
Set the pushing limit.
void setDistanceFromPlaneForGripper (double distance_from_plane_grasping_poses)
void setApproachingDistance (double approaching_distance)
void setPushingObjectDistance (double pushing_object_distance)
void computeBlockPredicates (bool print=false, uint pushing_method=ORTHOGONAL_PUSHING, double resolution=0.05, double pushing_limit=0.2, double minimum_distance=0.02, bool pushing_until_graspable=true)
Get block predicates.
void computeBlockGraspPredicates (bool print=false, double minimum_grasping_distance=0.02)
Get block grasp predicates.
void testFcl ()
void testFcl2 ()
void computePrincipalDirectionsConvexHull ()
compute the principal directions of the objects using the point cloud of the convex hull. (The results should be not as good as computePrincipalDirections())
void computePrincipalDirectionsConcaveHull ()
void computePrincipalDirections ()
compute the principal directions of the objects.
void voxelizeObjects (double leaf_size=0.01f)
Voxelize objects.
void voxelizeFullObjects (double leaf_size=0.01f)
Voxelize Full Objects.
void buildFullObjectsCloud (std::vector< PointCloudT > &occluded_sides)
void visualComputeBlockPredicates (Visualizer viewer, uint obj_idx, uint dir_idx, bool visualization=true, bool print=true, uint pushing_method=ORTHOGONAL_PUSHING, double resolution=0.05, double pushing_limit=0.2, double minimum_distance=0.02, bool pushing_until_graspable=true)
Compute the block predicates.
void viewerAddConvexHulls (Visualizer viewer, uint idx)
Show the convex hulls.
void viewerAddConcaveHulls (Visualizer viewer, uint idx)
Show the concave hulls.
void viewerAddPrincipalDirections (Visualizer viewer, uint i)
Shows the projections of the principal directions of a specific object.
void viewerAddPrincipalDirections (Visualizer viewer)
Add to the viewer associated to the class the projections of the principal directions of each object.
void viewerAddOriginalPrincipalDirections (Visualizer viewer, uint i)
Add to the viewer associated to the class the projections of the original principal directions of each object.
void cleanPrincipalDirections (Visualizer viewer, uint i)
Remove from the the viewer associated to the class the principal directions of a specific object.
void cleanPolygonalMesh (Visualizer viewer)
Remove the viewer associated to the class all the polygonal mesh.
void viewerAddPlaneNormal (Visualizer viewer)
void viewerAddObjectsClouds (Visualizer viewer)
void viewerAddRichObjectsClouds (Visualizer viewer)
void viewerAddFullObjectsClouds (Visualizer viewer)
void viewerAddPlaneCloud (Visualizer viewer)
void viewerAddProjections (Visualizer viewer)
void viewerAddProjection (Visualizer viewer, uint idx)
void viewerAddProjection (Visualizer viewer, uint idx, float r, float g, float b)
void viewerAddProjectionConvexHull (Visualizer viewer, uint idx)
void viewerAddProjectionConvexHull (Visualizer viewer, uint idx, float r, float g, float b)
void viewerAddPlaneConvexHull (Visualizer viewer, double r=1, double g=1, double b=1)
void viewerAddObjectsLabel (Visualizer viewer)
Show the labels in the viewer as 3D text.
void viewerShowGripperModel (Visualizer viewer, double r=1, double g=1, double b=1)
void viewerShowClosedGripperModel (Visualizer viewer, double r=1, double g=1, double b=1)
void viewerAddObjectsTransfomed (Visualizer viewer)
Show in the viewer associated to the class a transformed object. ONLY FOR DEBUGGING PURPOSE - USELESS.
void viewerAddGraspingPose (Visualizer viewer, uint idx)
void viewerAddGraspingPoses (Visualizer viewer)
void viewerAddPushingGraspingPose (Visualizer viewer, uint obj_idx, uint dir_idx)
Add to the viewer the grasping pose estimated after having pushed the object.
void viewerAddApproachingPose (Visualizer viewer, uint idx)
void viewerAddApproachingPoses (Visualizer viewer)
uint getNumObjects ()
std::vector< ObjectFull > getFullObjects ()
std::vector< OBB > getOBBObjects ()
std::vector< BlocksPredicate > getBlockPredicates ()
std::vector< std::vector< uint > > getOnTopPredicates ()
std::vector< std::vector< uint > > getBlockGraspPredicates ()
std::vector
< PrincipalDirectionsProjected > getProjectedPrincipalDirections ()
std::vector
< OriginalPrincipalDirections > getOriginalPrincipalDirections ()
std::vector< GraspingPose > getGraspingPoses ()
std::vector< GraspingPose > getApproachingPoses ()
std::vector< PushingPose > getPushingPoses ()
std::vector< PushingGraspingPose > getPushingGraspingPoses ()
ExecutionTimes getExecutionTimes ()
double getPushingObjectDistance ()
std::vector< PushingLength > getPushingLengths ()
Return the pushing lengths per each object and per each direction.
void reset ()
Delete all the data ot the class.
void printExecutionTimes ()
void printPushingLengths ()
void printPushingEEDistances ()
void resetPushingLengths ()
void resetPushingDistance ()
Private Types
typedef pcl::PointXYZRGBA PointT
typedef pcl::PointCloud< PointT > PointCloudT
typedef boost::shared_ptr
< pcl::visualization::PCLVisualizer > Visualizer
Private Member Functions
bool areObjectCollidingFcl (uint idx_1, fcl::Transform3f tf, uint idx_2)
Check with the fcl library yf the transformed object is colliding with another one.
bool isEEColliding (uint idx, fcl::Transform3f tf, double &distance)
Check if the gripper is colliding with object indexed by "idx".
bool isClosedGripperModelColliding (uint idx, fcl::Transform3f tf, double &distance)
bool isOpenGripperModelColliding (uint idx, fcl::Transform3f tf, double &distance)
Check if the open gripper model is colliding with other objects.
FclMesh getGripperMesh ()
Get the mesh of the gripper model.
FclMesh getClosedFingersMesh ()
Get the mesh of the closed gripper model.
FclMesh getGripperModelMesh ()
Eigen::Vector3f pointT2vector3f (PointT point)
Convert from PointT to Eigen::Vector3f.
FclMesh pcl2FclConvexHull (uint idx)
FclMesh pcl2FclConvexHull (PointCloudT convex_hull_cloud, std::vector< pcl::Vertices > convex_hull_indices)
void fcl2EigenTransform (Eigen::Vector4f &translate, Eigen::Quaternionf &q_rot, fcl::Transform3f &tf)
void eigen2FclTransform (Eigen::Vector4f &translate, Eigen::Quaternionf &q_rot, fcl::Transform3f &tf)
void eigen2FclTransform (Eigen::Vector3f &translate, Eigen::Quaternionf &q_rot, fcl::Transform3f &tf)
void eigen2FclRotation (Eigen::Quaternionf &q_rot, fcl::Matrix3f &rot)
void eigen2FclRotation (Eigen::Matrix3f eig_rot, fcl::Matrix3f &rot)
void translate (PointCloudT &cloud1, PointCloudT &cloud2, Eigen::Vector4f &translation)
Test function.
void computeSurfaceGraspPoint (Eigen::Vector3f &surface_point, uint idx)
Get the centroid of the grasping pose as the surface point of the object which projection on the table plane is similar to the centroid.
bool refineSimpleGraspingPose (GraspingPose &gp, double translation_step=0.005, double distance_from_plane=0.01)
Private Attributes
double pushing_limit
double pushing_step
double pushing_object_distance
Distance between the tcp and the object for the first point of the pushing action.
uint n_objects
number of objects
std::vector< BlocksPredicate > blocks_predicates
std::vector< std::vector< uint > > on_top_predicates
std::vector< std::vector< uint > > block_grasp_predicates
struct
CTableClearingPlanning::EndEffector ee_simple_model
end effector simple model
struct
CTableClearingPlanning::GripperModel gripper_model
ExecutionTimes executionTimes
Data regarding the elapsed times of the several phases of the algorithm.
PointCloudT original_cloud
Original point cloud (The oen seen by the Kinect)
PointCloudT plane_cloud
PointCloudT plane_convex_hull_2d
std::vector< pcl::Vertices > plane_convex_hull_indices
std::vector< PointCloudT > objects
vector of objects point cloud
pcl::PointCloud< pcl::PointXYZL > objects_labeled_cloud
A single point cloud with the objects are labelled.
std::vector< PointCloudT > rich_objects
Add also the projections onto the table plane to the segmented objects.
std::vector< ObjectFull > objects_full
std::vector< PointCloudT > projections
projections of the segmented objects onto the table plane
std::vector< PointCloudT > convex_hull_objects
vector of the convex hull of each object
std::vector< PointCloudT > concave_hull_objects
vector of the concave hull of each object
std::vector
< PrincipalDirectionsProjected > principal_directions_objects
principal directions projected onto the table plane
std::vector
< OriginalPrincipalDirections > original_principal_directions_objects
Original principal directions = principal components.
std::vector< std::vector
< pcl::Vertices > > convex_hull_vertices
std::vector< std::vector
< pcl::Vertices > > concave_hull_vertices
vertices of the hulls
std::vector< PushingLength > pushing_lengths
The pushing length for each object and pushing direction.
std::vector< PushingGraspingPose > pushing_grasping_poses
std::vector< OBB > obb_objects
Oriented Bounding Box of each object.
std::vector< GraspingPose > grasping_poses
std::vector< GraspingPose > approaching_poses
Grasping and approaching poses.
double approaching_distance
Distance between the approaching distance and the grasping pose.
double distance_from_plane_grasping_poses
Parameter which specifies how much the gripper should be far from the table in the graspin pose (This is a safety measure in roder to avoid collision between the gripper and the table)
std::vector< PushingPose > pushing_poses
Pose of the end effector when push.
std::vector< PointCloudT > concave_hull_projections
std::vector< std::vector
< pcl::Vertices > > concave_hull_vertices_projections
std::vector< PointCloudT > convex_hull_projections
std::vector< std::vector
< pcl::Vertices > > convex_hull_vertices_projections
pcl::ModelCoefficients plane_coefficients
Eigen::Vector3f plane_normal
normals of the plane
Eigen::Vector3f plane_origin
an arbitrary point of the plane to act like origin
Static Private Attributes
static const double PUSHING_STEP = 1.5
static const double PUSHING_OBJECT_DISTANCE = 0.05
static const double APPROACHING_DISTANCE = 0.10
static const double DISTANCE_FROM_PLANE_GRASPING_POSES = 0.01
Detailed Description
Definition at line 175 of file table_clearing_planning.h.
Constructor & Destructor Documentation
CTableClearingPlanning::CTableClearingPlanning (std::vector< PointCloudT > & objects)
Parameters
objects
Definition at line 14 of file table_clearing_planning.cpp.
References approaching_distance, distance_from_plane_grasping_poses, n_objects, objects, pushing_object_distance, and pushing_poses.
Member Function Documentation
bool CTableClearingPlanning::areObjectCollidingFcl (uint idx_1, fcl::Transform3f tf, uint idx_2) private
[long description]
Parameters
idx_1 index of the object to transform
tf transformation of the object
idx_2 index of the object to check if collides with transformed object 1
Returns
True if the transformed object 1 and the object 2 collides
Definition at line 57 of file table_clearing_planning.cpp.
References pcl2FclConvexHull().
Referenced by computeBlockPredicates(), and visualComputeBlockPredicates().
bool CTableClearingPlanning::isEEColliding (uint idx, fcl::Transform3f tf, double & distance) private
Check if the gripper is colliding with object indexed by "idx". NOTE: this function is used only when you choose a pushing pose parallel to the table plane. The usggested one is the vertical/ortoghonal one.
Returns
true if there is a collision with object indexed by "idx"
Definition at line 182 of file table_clearing_planning.cpp.
References getGripperMesh(), and pcl2FclConvexHull().
Referenced by computeBlockPredicates(), and visualComputeBlockPredicates().
bool CTableClearingPlanning::isClosedGripperModelColliding (uint idx, fcl::Transform3f tf, double & distance) private
Collission checking for the case we push in orhtoganl mode
Parameters
[in] idx Index of the object
[in] tf tf of the gripper
[out] distance distance to the closest point
Returns
true if there is a collision with object indexed by "idx"
Definition at line 242 of file table_clearing_planning.cpp.
References getClosedFingersMesh(), and pcl2FclConvexHull().
Referenced by computeBlockPredicates(), and visualComputeBlockPredicates().
bool CTableClearingPlanning::isOpenGripperModelColliding (uint idx, fcl::Transform3f tf, double & distance) private
Check if the open gripper model is colliding with other objects
Parameters
[in] idx Index of the object
[in] tf tf of the gripper
[out] distance distance to the closest point
Returns
true if there is collision, false otherwise
Definition at line 304 of file table_clearing_planning.cpp.
References pcl2FclConvexHull().
Referenced by computeBlockGraspPredicates(), computeBlockPredicates(), and visualComputeBlockPredicates().
CTableClearingPlanning::FclMesh CTableClearingPlanning::getGripperMesh () private
[long description]
Returns
FclMesh containing the vertices and the triangles
Definition at line 367 of file table_clearing_planning.cpp.
References ee_simple_model.
Referenced by isEEColliding().
CTableClearingPlanning::FclMesh CTableClearingPlanning::getClosedFingersMesh () private
[long description]
Returns
FclMesh containing the vertices and the triangles
Definition at line 405 of file table_clearing_planning.cpp.
References CTableClearingPlanning::GripperModel::closed_cloud, and CTableClearingPlanning::GripperModel::closed_vertices.
Referenced by isClosedGripperModelColliding().
Eigen::Vector3f CTableClearingPlanning::pointT2vector3f (PointT point) private
Parameters
[in] point point to convert
Returns
point in Eigen::Vector3f format
Definition at line 480 of file table_clearing_planning.cpp.
Referenced by computeProjectionsOnTable().
CTableClearingPlanning::FclMesh CTableClearingPlanning::pcl2FclConvexHull (uint idx) private
Convert the convex hull of the object with index "idx" from pcl to fcl format
Parameters
idx index of the convex hull to convert
Returns
struct which contains the vertices and triangle for the fcl format
Definition at line 490 of file table_clearing_planning.cpp.
References convex_hull_objects.
Referenced by areObjectCollidingFcl(), isClosedGripperModelColliding(), isEEColliding(), and isOpenGripperModelColliding().
CTableClearingPlanning::FclMesh CTableClearingPlanning::pcl2FclConvexHull (PointCloudT convex_hull_cloud, std::vector< pcl::Vertices > convex_hull_indices) private
Convert the convex hull from pcl to fcl format
Parameters
convex_hull_cloud
convex_hull_indices
Returns
Fcl mesh
Definition at line 537 of file table_clearing_planning.cpp.
void CTableClearingPlanning::computeSurfaceGraspPoint (Eigen::Vector3f & surface_point, uint idx) private
Get the centroid of the grasping pose as the surface point of the object which projection on the table plane is similar to the centroid.
Parameters
[out] surface_point surface point
[in] idx Index of the object
Definition at line 1134 of file table_clearing_planning.cpp.
References objects, principal_directions_objects, and projections.
Referenced by computeSimpleHeuristicGraspingPoses().
bool CTableClearingPlanning::refineSimpleGraspingPose (GraspingPose & gp, double translation_step = 0.005, double distance_from_plane = 0.01) private
Refines the input grasping pose, that is if the gripper central point is further than the plane. It satisfy the following equation
a*x + b*y + c*(z+offset) * d > 0
If such an inequality is true the grasping pose has to be refine, it is translated along its approaching direction by translation_step until that inequalities is no more satisfied. Note the this method doesn't check if after the refining the grasp is still feasible, bu the height of the object should be coherent with the one of the distance from the plane.
Parameters
gp Input grasping pose
translation_step
distance_from_plane minimum distance from the plane, bigger it is further the plane it is.
Returns
True if there was initially in collision.
Definition at line 1163 of file table_clearing_planning.cpp.
References CTableClearingPlanning::GripperModel::open_cloud, and plane_coefficients.
Referenced by computeSimpleHeuristicGraspingPoses().
void CTableClearingPlanning::setGripperSimpleModel (double height, double deep, double width, double distance_plane)
Set the dimension of the bounding box of the gripper. This model will be used during the computation of the block predicates if you choose PARALLEL_PUSHING(not recommended). You don't need to set this model if you do not use the PARALLEL_PUSHING. Here the gripper is considered as a cube.
Parameters
[in] height Dimension of the gripper orthogonal to the plane during the pushing action
[in] deep Dimension of the gripper parallel to pushing direction during the pushing action
[in] width Dimension of the gripper orthogonal to pushing direction during the pushing action
[in] distance_plane Distance in meters from the table plane during the pushing action
Definition at line 761 of file table_clearing_planning.cpp.
References CTableClearingPlanning::EndEffector::distance_plane, and ee_simple_model.
void CTableClearingPlanning::setGripperModel (double opening_width, double closing_width, double finger_width, double deep, double height, double closing_height)
Set the fingers model. The origin is located at height/2, deep/2 and (opening_width + finger_width*2)/2
Parameters
opening_width
closing_width
finger_width [description]
deep [description]
height [description]
closing_height [description]
Definition at line 813 of file table_clearing_planning.cpp.
References CTableClearingPlanning::GripperModel::closed_cloud, CTableClearingPlanning::GripperModel::closed_vertices, and CTableClearingPlanning::GripperModel::open_cloud.
void CTableClearingPlanning::setPlanePointCloud (PointCloudT plane_cloud)
Parameters
plane_cloud
Definition at line 44 of file table_clearing_planning.cpp.
void CTableClearingPlanning::setOriginalPointCloud (PointCloudT original_cloud)
Parameters
[in] original_cloud
Definition at line 40 of file table_clearing_planning.cpp.
References original_cloud.
void CTableClearingPlanning::setObjectsPointCloud (std::vector< PointCloudT > & objects, bool convert_to_label = false)
Parameters
[in] objects vector of point clouds, one per object
[in] convert_to_label true if you want to create a unique point cloud labeled,
Definition at line 3482 of file table_clearing_planning.cpp.
References objects, objects_labeled_cloud, pushing_lengths, and pushing_poses.
void CTableClearingPlanning::setPlaneCoefficients (pcl::ModelCoefficients & plane_coefficients)
Parameters
[in] plane_coefficients coefficients of the table plane
Definition at line 3518 of file table_clearing_planning.cpp.
References plane_coefficients, plane_normal, and plane_origin.
void CTableClearingPlanning::testFclDistance ()
You should see the code to understand how this work. There is a model of a simple pyramid, and a transformation defined in order to check that the distance is correct.
Definition at line 1060 of file table_clearing_planning.cpp.
void CTableClearingPlanning::computeOBBObjects (bool refine_centroids = true)
Parameters
refine_centroids True if you want to refine the centroid by computing the mean of the bounding box
Definition at line 629 of file table_clearing_planning.cpp.
References computePrincipalDirections(), n_objects, obb_objects, objects, plane_normal, principal_directions_objects, and projections.
void CTableClearingPlanning::computeSimpleHeuristicGraspingPoses (bool vertical_poses = PCA_GRASPING)
Compute the grasping pose with a simple heuristic. Gripper centered at the centroid with rotation aligned to the principal axes. The contact point is choosen to be the nearest point which projection on the table plane is the enarest on the projection of the centroid.
Parameters
vertical_poses If it is set to true consider only vertical poses, with respect the table.
Definition at line 683 of file table_clearing_planning.cpp.
References approaching_distance, approaching_poses, computeSurfaceGraspPoint(), distance_from_plane_grasping_poses, n_objects, original_principal_directions_objects, plane_normal, principal_directions_objects, and refineSimpleGraspingPose().
void CTableClearingPlanning::computeRichConvexHulls (bool rand_ = true)
Parameters
rand_ If it is true a random color is assigned to each convex hull
Definition at line 3134 of file table_clearing_planning.cpp.
References convex_hull_objects, objects, projections, and rich_objects.
Referenced by computeBlockPredicates().
void CTableClearingPlanning::computeOnTopPredicates (double th1 = 100, double th2 = 100, bool print = false)
To decide if an oject is on top ot the other one, we work with the convex hulls of the projections and the projected points. Since the pow of the kinect make that the on top objects hide part of the bottom objects the strategy is the following: 1) for objet 1 check if its points (choose randomly) lies inside the convex hull of the other one 2) if a point lieas inside the convex hull of the other one, tdo the same with the object 2. 3) if object 1 lies inside the convex hull of the object 2, but object 2 does'nt, the object 1 is on top of object 2. MAYBE A EROSION TECHNIQUE WILL BE REQUIRED IN ORDER TO AVOID SITUATIONS WHERE THE PROJECTED POINTS ARE TOO MUCH CLOSE
Parameters
th1 threshold: how many points of the objects which is on the top can lie inside the convex hull of the other
th2 The inverse of th1, a correct balance between them we can achieve a nice result
Definition at line 1291 of file table_clearing_planning.cpp.
References computeProjectionsConvexHull(), executionTimes, n_objects, and projections.
void CTableClearingPlanning::setPushingStep (double pushing_step)
If it is not setted a default value will be used. The pushing step is here defined as the maximum times of the OBB dimension to be pushed. (e.g. : If the pushing_step is 1.5 considering to push ht eojbect 1 in direction 1 it is pushed for 1.5 the OBB dimension relative to direction 1 (which is the OBB.deep))
Parameters
[in] pushing_step Desired value for the pushing limit.
Definition at line 1347 of file table_clearing_planning.cpp.
void CTableClearingPlanning::setDistanceFromPlaneForGripper (double distance_from_plane_grasping_poses)
Minimum distance of the gripper from the plane, this is in case there are poses too close the plane. The default values is 1 cm.
Parameters
distance_from_plane_grasping_poses
Definition at line 1351 of file table_clearing_planning.cpp.
References distance_from_plane_grasping_poses.
void CTableClearingPlanning::setApproachingDistance (double approaching_distance)
distance in meter between the grasping pose and the approaching pose. The approaching pose is the pose of the gripper where it will be opened.
Parameters
approaching_distance Distance in meters
Definition at line 1355 of file table_clearing_planning.cpp.
References approaching_distance.
void CTableClearingPlanning::setPushingObjectDistance (double pushing_object_distance)
This distance is the distance of the end effector from the object, it is like an offset.
Parameters
pushing_object_distance distance from the objects, in meters
Definition at line 1359 of file table_clearing_planning.cpp.
References pushing_object_distance.
void CTableClearingPlanning::computeBlockPredicates (bool print = false, uint pushing_method = ORTHOGONAL_PUSHING, double resolution = 0.05, double pushing_limit = 0.2, double minimum_distance = 0.02, bool pushing_until_graspable = true)
This method computes the block predicates for a each object by detecting collision with the other objects, determining also what object collides with the current one, along each principal direction. The length of the push considered in saved in the private memeber. THis functions also computes the new grasping poses for a pose in which the object, when it has been pushed, can be grasped (If it is not possible grasping it in any pose until having reached the maxmimum pushing distance [pushing_limit] the returned grasping pose will be the one at the final checked pose).
Parameters
[in] print True if you want to print in the terminal the predicates
[in] pushing_method There exist two pushing method: 1) ORTHOGONAL_PUSHING is the one recommended and it referes to put the end effector orthogonal to the plane 2) PARALLEL_PUSHING refers to the end effector approaching direction is parallel to the plane (Not recommended)
[in] resolution It specifies the resolution of checking for the pushing action
[in] pushing_limit It specifies the maximum limit (in meters) the method checks for collision and grasping. N Note that as soon as it finds a pushing length for which the next pose corresponds to a feasible grasp it checks no more for further distances
[in] minimum_distance Minimum distance from the closest object to consider to future grasp a feasible one.
[in] pushing_until_graspable pushing_until_graspable True if the algorithm push until the object can be grasped, otherwise it pushes for for a length equal to the dimension relative to the pushing direction. The distanceof the end effector during pushing are anyway computed.
Definition at line 1363 of file table_clearing_planning.cpp.
References areObjectCollidingFcl(), ExecutionTimes::average_ee_collision, ExecutionTimes::average_objects_collision, PrincipalDirectionsProjected::centroid, computePrincipalDirections(), computeProjectionsOnTable(), computeRichConvexHulls(), convex_hull_objects, PrincipalDirectionsProjected::dir4, CTableClearingPlanning::EndEffector::distance_plane, ExecutionTimes::ee_collisions, ee_simple_model, executionTimes, isClosedGripperModelColliding(), isEEColliding(), isOpenGripperModelColliding(), n_objects, obb_objects, objects, ExecutionTimes::objects_collisions, plane_normal, plane_origin, principal_directions_objects, pushing_lengths, pushing_object_distance, and pushing_poses.
void CTableClearingPlanning::computeBlockGraspPredicates (bool print = false, double minimum_grasping_distance = 0.02)
This method computes the block grasp predicates for each object by detecting collision of the open gripper model with the other objects.
Parameters
print True if you want to print in the terminal the predicates.
minimum_grasping_distance Minimum distance to the closest object to consider the grasp as collision free
Definition at line 2930 of file table_clearing_planning.cpp.
References executionTimes, isOpenGripperModelColliding(), and n_objects.
void CTableClearingPlanning::computePrincipalDirections ()
This is better because the others that use the hulls the amount of points of the hulls depends on the complexity of the shape, so the principal directions would be affected by the complexity of the shape and not on the quanrity of points. This method also include a verse detection in order to have alway dir3 to the right of dir1 with respect the top of the table.
Definition at line 3320 of file table_clearing_planning.cpp.
References PrincipalDirectionsProjected::centroid, PrincipalDirectionsProjected::dir4, objects, original_principal_directions_objects, plane_coefficients, plane_normal, and principal_directions_objects.
Referenced by computeBlockPredicates(), and computeOBBObjects().
void CTableClearingPlanning::voxelizeObjects (double leaf_size = 0.01f)
Remember that this will affect also the on top predicates
Parameters
leaf_size Leaf size
Definition at line 3404 of file table_clearing_planning.cpp.
References objects.
void CTableClearingPlanning::voxelizeFullObjects (double leaf_size = 0.01f)
Voxelize Full Objects
Parameters
leaf_size Leaf size
Definition at line 3416 of file table_clearing_planning.cpp.
void CTableClearingPlanning::visualComputeBlockPredicates (Visualizer viewer, uint obj_idx, uint dir_idx, bool visualization = true, bool print = true, uint pushing_method = ORTHOGONAL_PUSHING, double resolution = 0.05, double pushing_limit = 0.2, double minimum_distance = 0.02, bool pushing_until_graspable = true)
This method computes the block predicates for a certain object and a certain direction by detecting collision with the other objects, determining also what object collides with the current one. It also add the viewer all the relative information in order to have a visual feedback of the process of computing the block predicates. The block predicates are then saved in the private member "blocks_predicates".
Parameters
[in] obj_idx Index of the object
[in] dir_idx Index of the direction [1,2,3,4]
[in] visualization True to enable the visualization
[in] print True to print in the terminal each block predicate
[in] pushing_until_graspable True if the algorithm push until the object can be grasped, otherwise it pushes for for a length equal to the dimension relative to the pushing direction. The distanceof the end effector during pushing are anyway computed.
Definition at line 2147 of file table_clearing_planning.cpp.
References areObjectCollidingFcl(), PrincipalDirectionsProjected::centroid, CTableClearingPlanning::GripperModel::closed_cloud, CTableClearingPlanning::GripperModel::closed_vertices, convex_hull_objects, PrincipalDirectionsProjected::dir4, CTableClearingPlanning::EndEffector::distance_plane, ExecutionTimes::ee_collisions, ee_simple_model, executionTimes, isClosedGripperModelColliding(), isEEColliding(), isOpenGripperModelColliding(), n_objects, obb_objects, objects, ExecutionTimes::objects_collisions, CTableClearingPlanning::GripperModel::open_cloud, plane_normal, plane_origin, principal_directions_objects, pushing_lengths, pushing_object_distance, and pushing_poses.
void CTableClearingPlanning::viewerAddConvexHulls (Visualizer viewer, uint idx)
Parameters
[in] idx index of the object to show
Definition at line 3106 of file table_clearing_planning.cpp.
References convex_hull_objects, and n_objects.
void CTableClearingPlanning::viewerAddConcaveHulls (Visualizer viewer, uint idx)
Parameters
[in] idx index of the object to show
Definition at line 3126 of file table_clearing_planning.cpp.
void CTableClearingPlanning::viewerAddPrincipalDirections (Visualizer viewer, uint i)
Parameters
[in] i index of the object
Definition at line 3551 of file table_clearing_planning.cpp.
References principal_directions_objects.
Referenced by viewerAddPrincipalDirections().
void CTableClearingPlanning::cleanPrincipalDirections (Visualizer viewer, uint i)
Parameters
[in] i Index of the object
Definition at line 3719 of file table_clearing_planning.cpp.
void CTableClearingPlanning::viewerAddProjections (Visualizer viewer)
Add to the viewer the projections. Moreover each projection point cloud is colored with a random color.
Parameters
viewer viewer
Definition at line 4205 of file table_clearing_planning.cpp.
References projections.
void CTableClearingPlanning::viewerAddProjection (Visualizer viewer, uint idx)
Add to the viewer a projection colored with a random color.
Parameters
viewer viewer
idx index of the object
Definition at line 4243 of file table_clearing_planning.cpp.
References projections.
void CTableClearingPlanning::viewerAddProjection (Visualizer viewer, uint idx, float r, float g, float b)
Add to the viewer a projection colored with a specifed color.
Parameters
viewer viewer
idx index of the object
r red channel [0-255]
g green channel [0-255]
b blue channel [0-255]
Definition at line 4279 of file table_clearing_planning.cpp.
References projections.
void CTableClearingPlanning::viewerAddProjectionConvexHull (Visualizer viewer, uint idx)
Add to the viewer the convex hull of the projection of the idx object.
Parameters
viewer viewer
idx index of the object
Definition at line 4304 of file table_clearing_planning.cpp.
References projections.
void CTableClearingPlanning::viewerAddProjectionConvexHull (Visualizer viewer, uint idx, float r, float g, float b)
Add to the viewer the convex hull of the projection of the idx object with the color of the convex hull given as input.
Parameters
viewer viewer
idx index of the object
r red channel [0-255]
g green channel [0-255]
b blue channel [0-255]
Definition at line 4333 of file table_clearing_planning.cpp.
References projections.
void CTableClearingPlanning::viewerAddPlaneConvexHull (Visualizer viewer, double r = 1, double g = 1, double b = 1)
Parameters
viewer [description]
r [description]
g [description]
b [description]
Definition at line 3877 of file table_clearing_planning.cpp.
void CTableClearingPlanning::viewerAddObjectsLabel (Visualizer viewer)
It is not working, I don't know why.
Parameters
[in] viewer { parameter_description }
Definition at line 3901 of file table_clearing_planning.cpp.
References principal_directions_objects.
void CTableClearingPlanning::viewerShowGripperModel (Visualizer viewer, double r = 1, double g = 1, double b = 1)
Add in the viewer the open gripper model with colors specified as input [0-1]. The gripper is not transformed, so you will see it at the frame of the point cloud.
Parameters
viewer [description]
r [description]
g [description]
b [description]
Definition at line 4121 of file table_clearing_planning.cpp.
References CTableClearingPlanning::GripperModel::open_cloud.
void CTableClearingPlanning::viewerShowClosedGripperModel (Visualizer viewer, double r = 1, double g = 1, double b = 1)
Add in the viewer the closed gripper model with colors specified as input [0-1]. The gripper is not transformed, so you will see it at the frame of the point cloud.
Parameters
viewer
r [0-255]
g [0-255]
b [0-255]
Definition at line 4146 of file table_clearing_planning.cpp.
References CTableClearingPlanning::GripperModel::closed_cloud, and CTableClearingPlanning::GripperModel::closed_vertices.
void CTableClearingPlanning::viewerAddPushingGraspingPose (Visualizer viewer, uint obj_idx, uint dir_idx)
Add to the viewer the grasping pose estimated after having pushed the object
Parameters
viewer
obj_idx index of the obejct
dir_idx index of the direction
Definition at line 3964 of file table_clearing_planning.cpp.
References CTableClearingPlanning::GripperModel::open_cloud.
std::vector< PrincipalDirectionsProjected > CTableClearingPlanning::getProjectedPrincipalDirections ()
Get the projected principal directions
Returns
projected principal directions
Definition at line 4067 of file table_clearing_planning.cpp.
References principal_directions_objects.
std::vector< PushingLength > CTableClearingPlanning::getPushingLengths ()
Return the pushing lengths per each object and per each direction
Definition at line 4095 of file table_clearing_planning.cpp.
References pushing_lengths.
void CTableClearingPlanning::reset ()
Delete all the data ot the class
Definition at line 4172 of file table_clearing_planning.cpp.
References concave_hull_objects, convex_hull_objects, obb_objects, objects, original_cloud, original_principal_directions_objects, principal_directions_objects, projections, and rich_objects.
void CTableClearingPlanning::printExecutionTimes ()
Print in the terminal the several execution times.
Definition at line 4195 of file table_clearing_planning.cpp.
References ExecutionTimes::average_ee_collision, ExecutionTimes::average_objects_collision, ExecutionTimes::ee_collisions, executionTimes, and ExecutionTimes::objects_collisions.
Field Documentation
pcl::ModelCoefficients CTableClearingPlanning::plane_coefficients private
coefficients of the plane model ax+by+cz+d=0
Definition at line 286 of file table_clearing_planning.h.
Referenced by computePrincipalDirections(), computePrincipalDirectionsConvexHull(), refineSimpleGraspingPose(), and setPlaneCoefficients().
The documentation for this class was generated from the following files:
/home/ncovallero/iri-lab/labrobotica/algorithms/table_clearing_planning/trunk/src/table_clearing_planning.h
/home/ncovallero/iri-lab/labrobotica/algorithms/table_clearing_planning/trunk/src/table_clearing_planning.cpp