Table Clearing Planning Module: CScene_Perception_Planning Class Reference
CScene_Perception_Planning Class Reference
This class computes the predicates of the table top objects for the planning part The class needs as input the segmented objects and the table plane coefficients. Be sure to given the objects in input with respect the desired reference frame.
#include <scene_perception_planning.h>
Public Member Functions
CScene_Perception_Planning (std::vector< PointCloudT > &objects)
Initialize the class with the objects.
void setGripperSimpleModel (double height, double deep, double width, double distance_plane)
Set the gripper model.
void setOriginalPointCloud (PointCloudT original_cloud)
Set the original point cloud, the one used for the segmentation.
void setObjectsPointCloud (std::vector< PointCloudT > &objects)
set point clouds of the objects, reference to project the principal direction to the plane: http://www.maplesoft.com/support/help/Maple/view.aspx?path=MathApps%2FProjectionOfVectorOntoPlane
void setPlaneCoefficients (pcl::ModelCoefficients &plane_coefficients)
Set the coefficients of the table plane.
void testTranslation (uint idx)
void computeAABBObjects (bool refine_centroids=true)
Compute the Axis Aligned Bounding Box of each object.
void computeConvexHulls ()
Compute the convex hull of each object.
void computeConcaveHulls ()
Compute the concave hull of each object.
void computeProjectionsOnTable ()
Compute the projections of the objects onto the table plane.
void computeProjectionsConvexHull ()
Compute the convex hulls of the projections onto the table plane.
void computeRichConvexHulls ()
Compute the convex hull of each object considering also the projections of the convex hulls on the plane. These points are then added to the original point cloud and the convex hull is recomputed. IMPORTANT: we can project all the coud and do the convex hull, so it is computed only once.
void computeRichConcaveHulls ()
Compute the concave hull of each object considering also the projections of the convex hulls on the plane. These points are then added to the original point cloud and the convex hull is recomputed. IMPORTANT: THE CONCAVE HULL IS NOT WELL IMPLEMENTED SEE: http://www.pointclouds.org/blog/gsoc/goleary/tutorials/concave_hull.php.
void computeOnTopPredicates ()
Compute the on predicates.
void setPushingLimit (double pushing_limit)
Set the pushing limit.
void computeBlockPredicates (bool print=false)
Get block predicates.
void testFcl ()
void testFcl2 ()
void computePrincipalDirectionsConvexHull ()
compute the principal directions of the objects using the point cloud of the convex hull. (The results should be not as good as computePrincipalDirections()) NOT VERSE DETECTION
void computePrincipalDirectionsConcaveHull ()
void computePrincipalDirections ()
compute the principal directions of the objects. This is better because the others that use the hulls the amount of points of the hulls depends on the complexity of the shape, so the principal directions would be affected by the complexity of the shape and not on the quanrity of points. This method also include a verse detection in order to have alway dir3 to the right of dir1 with respect the top of the table. dir1 ^ | dir4<--—>dir3 | dir2
void buildFullObjectsCloud (std::vector< PointCloudT > &occluded_sides)
void visualComputeBlockPredicates (Visualizer viewer, uint obj_idx, uint dir_idx, bool visualization=true, bool print=true)
Compute the block predicates.
void viewerAddConvexHulls (Visualizer viewer, uint idx)
Show the convex hulls.
void viewerAddConcaveHulls (Visualizer viewer, uint idx)
Show the concave hulls.
void viewerAddPrincipalDirections (Visualizer viewer, uint i)
Shows the projections of the principal directions of a specific object.
void viewerAddPrincipalDirections (Visualizer viewer)
Add to the viewer associated to the class the projections of the principal directions of each object.
void cleanPrincipalDirections (Visualizer viewer, uint i)
Remove from the the viewer associated to the class the principal directions of a specific object.
void cleanPolygonalMesh (Visualizer viewer)
Remove the viewer associated to the class all the polygonal mesh.
void viewerAddPlaneNormal (Visualizer viewer)
void viewerAddObjectsClouds (Visualizer viewer)
void viewerAddRichObjectsClouds (Visualizer viewer)
void viewerAddFullObjectsClouds (Visualizer viewer)
void viewerAddObjectsLabel (Visualizer viewer)
Show the labels in the viewer as 3D text.
void viewerAddObjectsTransfomed (Visualizer viewer)
Show in the viewer associated to the class a transformed object. ONLY FOR DEBUGGING PURPOSE - USELESS.
uint getNumObjects ()
std::vector< ObjectFull > getFullObjects ()
std::vector< AABB > getAABBObjects ()
Detailed Description
Definition at line 69 of file scene_perception_planning.h.
Constructor & Destructor Documentation
CScene_Perception_Planning::CScene_Perception_Planning (std::vector< PointCloudT > & objects)
Parameters
objects
Definition at line 10 of file scene_perception_planning.cpp.
Member Function Documentation
void CScene_Perception_Planning::setGripperSimpleModel (double height, double deep, double width, double distance_plane)
Set the dimension of the bounding box of the gripper. This model will be used during the computation of the block predicates
Parameters
[in] height Dimension of the gripper orthogonal to the plane during the pushing action
[in] deep Dimension of the gripper parallel to pushing direction during the pushing action
[in] width Dimension of the gripper orthogonal to pushing direction during the pushing action
[in] distance_plane Distance in meters from the table plane during the pushing action
Definition at line 316 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::setOriginalPointCloud (PointCloudT original_cloud)
Parameters
[in] original_cloud
Definition at line 23 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::setObjectsPointCloud (std::vector< PointCloudT > & objects)
Parameters
[in] objects vector of point clouds, one per object
Definition at line 1461 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::setPlaneCoefficients (pcl::ModelCoefficients & plane_coefficients)
Parameters
[in] plane_coefficients coefficients of the table plane
Definition at line 1467 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::computeAABBObjects (bool refine_centroids = true)
Parameters
refine_centroids True if you want to refine the centroid by computing the mean of the bounding box
Definition at line 265 of file scene_perception_planning.cpp.
References computePrincipalDirections().
void CScene_Perception_Planning::computeOnTopPredicates ()
To decide if an oject is on top ot the other one, we work with the convex hulls of the projections and the projected points. Since the pow of the kinect make that the on top objects hide part of the bottom objects the strategy is the following: 1) for objet 1 check if its points (choose randomly) lies inside the convex hull of the other one 2) if a point lieas inside the convex hull of the other one, tdo the same with the object 2. 3) if object 1 lies inside the convex hull of the object 2, but object 2 does'nt, the object 1 is on top of object 2. MAYBE A EROSION TECHNIQUE WILL BE REQUIRED IN ORDER TO AVOID SITUATIONS WHERE THE PROJECTED POINTS ARE TOO MUCH CLOSE
Definition at line 422 of file scene_perception_planning.cpp.
References computeProjectionsConvexHull().
void CScene_Perception_Planning::setPushingLimit (double pushing_limit)
If it is not setted a default value will be used. The pushing limit is here defined as the maximum length (in meters) you want to push the object and therefore it acts on the block predicates computation.
Parameters
[in] pushing_limit Desired value for the pushing limit.
Definition at line 467 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::computeBlockPredicates (bool print = false)
This method computes the block predicates for a each object by detecting collision with the other objects, determining also what object collides with the current one, along each principal direction. The length of the push considered in saved in the private memeber
Definition at line 472 of file scene_perception_planning.cpp.
References computePrincipalDirections(), computeProjectionsOnTable(), and computeRichConvexHulls().
void CScene_Perception_Planning::visualComputeBlockPredicates (Visualizer viewer, uint obj_idx, uint dir_idx, bool visualization = true, bool print = true)
This method computes the block predicates for a certain object and a certain direction by detecting collision with the other objects, determining also what object collides with the current one. It also add the viewer all the relative information in order to have a visual feedback of the process of computing the block predicates. The block predicates are then saved in the private member "blocks_predicates".
Parameters
[in] obj_idx Index of the object
[in] dir_idx Index of the direction [1,2,3,4]
[in] visualization True to enable the visualization
[in] print True to print in the terminal each block predicate
Definition at line 760 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::viewerAddConvexHulls (Visualizer viewer, uint idx)
Parameters
[in] idx index of the object to show
Definition at line 1187 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::viewerAddConcaveHulls (Visualizer viewer, uint idx)
Parameters
[in] idx index of the object to show
Definition at line 1195 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::viewerAddPrincipalDirections (Visualizer viewer, uint i)
Parameters
[in] i index of the object
Definition at line 1494 of file scene_perception_planning.cpp.
Referenced by viewerAddPrincipalDirections().
void CScene_Perception_Planning::cleanPrincipalDirections (Visualizer viewer, uint i)
Parameters
[in] i Index of the object
Definition at line 1577 of file scene_perception_planning.cpp.
void CScene_Perception_Planning::viewerAddObjectsLabel (Visualizer viewer)
It is not working, I don't know why.
Parameters
[in] viewer { parameter_description }
Definition at line 1703 of file scene_perception_planning.cpp.
The documentation for this class was generated from the following files:
/home/ncovallero/iri-lab/labrobotica/algorithms/table_clearing_planning/trunk/src/scene_perception_planning.h
/home/ncovallero/iri-lab/labrobotica/algorithms/table_clearing_planning/trunk/src/scene_perception_planning.cpp