Table Clearing Planning Module: /home/ncovallero/iri-lab/labrobotica/algorithms/table_clearing_planning/trunk/src/utilities.h File Reference
utilities.h File Reference
A file with utilities functions.
#include <iostream>
#include <stack>
#include <ctime>
#include <pcl/common/eigen.h>
Data Structures
struct AABB
Axis Aligned Bounding Box.
Functions
void tic ()
Start measuring the time.
void toc ()
Stop measuring the time and print the elapsed time.
Function Documentation
void tic ()
This function implements the tic Matlab function style to measure easily the elapsed time. reference: http://stackoverflow.com/questions/13485266/how-to-have-matlab-tic-toc-in-c
Usage:
tic();
..do something
toc();
Definition at line 4 of file utilities.cpp.
Referenced by EdgeProcessing::compute2DEdges(), and CTableClearingPlanning::computeBlockPredicates().
void toc ()
This function implements the toc Matlab function style to measure easily the elapsed time. reference: http://stackoverflow.com/questions/13485266/how-to-have-matlab-tic-toc-in-c
Usage:
tic();
..do something
toc();
Definition at line 7 of file utilities.cpp.
Referenced by EdgeProcessing::compute2DEdges(), and CTableClearingPlanning::computeBlockPredicates().